### ISSUE TITLE
画像同士の関連付けについて

### ISSUE THREAD

**Issue by kentarou1022** [Saigo1997/uzume#11]
やり方を検討する

**Comment by Saigo1997** [comment]
* 画像一覧ではグループ内の1枚だけ返すようにする
* グループ内の画像にはグループUUIDを振る
* グループ内で代表フラグを作って、1枚だけフラグを立てる
* 複数フラグが立っていた場合は最初の方を優先(その時は他の画像のフラグは折っておく)
* 1つもフラグが立っていない場合は1枚目を表示(その時はフラグを立てておく)
